# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
     entrypoint: bash
     args: [ './code/frontend//massage.sh', '$_REGION' ]
   - name: 'gcr.io/cloud-builders/docker'
     args: [ 'build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_BASENAME-app/fe', '.' ]
   - name: 'gcr.io/cloud-builders/docker'
     args: ['push', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_BASENAME-app/fe']
  # Finally, deploy the image to Cloud Run.
   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
     args:
       - 'run'
       - 'deploy'
       - '$_BASENAME-fe' # The name of your Cloud Run service
       - '--image=$_REGION-docker.pkg.dev/$PROJECT_ID/$_BASENAME-app/fe'
       - '--platform=managed'
       - '--region=$_REGION'
       - '--allow-unauthenticated' # Use this flag if you want public access to the service 
     dir: 'frontend'
options:
  logging: CLOUD_LOGGING_ONLY
  
substitutions:
  _REGION: us-central1
  _BASENAME: todo
